# Generated by Django 3.2.3 on 2021-05-29 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Material_Classifier', '0002_auto_20210529_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemclassificationpicture',
            name='picture_title',
        ),
        migrations.AddField(
            model_name='itemclassificationresults',
            name='item_results_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemclassificationresults',
            name='item_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Material_Classifier.itemclassificationpicture'),
        ),
    ]
