# Generated by Django 3.2.3 on 2021-05-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0003_auto_20210529_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclassificationpicture',
            name='picture_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
