# Generated by Django 3.2.3 on 2021-05-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0005_newsfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclassificationresults',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
