# Generated by Django 3.2.3 on 2021-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0008_incentiveoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiveoffers',
            name='offer_region',
            field=models.CharField(default='', max_length=150),
        ),
    ]
