# Generated by Django 3.2.3 on 2021-05-31 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Material_Classifier', '0009_incentiveoffers_offer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiveoffers',
            name='offer_users',
            field=models.ForeignKey(default='No Participants', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
