# Generated by Django 3.2.3 on 2021-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0010_alter_incentiveoffers_offer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiveoffers',
            name='offer_image',
            field=models.ImageField(blank=True, upload_to='offer_images/'),
        ),
        migrations.AlterField(
            model_name='incentiveoffers',
            name='offer_region',
            field=models.CharField(max_length=150),
        ),
    ]
