# Generated by Django 3.2.3 on 2021-06-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Material_Classifier', '0012_auto_20210601_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclassificationresults',
            name='date_disposed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incentiveoffers',
            name='offer_users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
