# Generated by Django 3.2.3 on 2021-06-02 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0013_auto_20210602_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclassificationresults',
            name='date_disposed',
            field=models.DateField(default=datetime.date(2021, 6, 2)),
        ),
    ]
