# Generated by Django 3.2.3 on 2021-06-02 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0014_alter_itemclassificationresults_date_disposed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclassificationresults',
            name='date_disposed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
