# Generated by Django 3.2.3 on 2021-06-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0015_alter_itemclassificationresults_date_disposed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemclassificationresults',
            name='date_disposed',
        ),
    ]
