# Generated by Django 3.2.3 on 2021-06-02 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0016_remove_itemclassificationresults_date_disposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclassificationresults',
            name='dadate_disposed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
