# Generated by Django 3.2.3 on 2021-06-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0017_itemclassificationresults_dadate_disposed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemclassificationresults',
            old_name='dadate_disposed',
            new_name='date_disposed',
        ),
    ]
