# Generated by Django 3.2.3 on 2021-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0018_rename_dadate_disposed_itemclassificationresults_date_disposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='is_governmental',
            field=models.BooleanField(default=False),
        ),
    ]
