# Generated by Django 3.2.3 on 2021-06-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0019_newsfeed_is_governmental'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
