# Generated by Django 3.2.3 on 2021-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0020_newsfeed_is_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150)),
                ('municipality_link', models.CharField(max_length=250)),
                ('extra_link_1', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
