# Generated by Django 3.2.3 on 2021-06-05 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0021_usefullinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquieries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquery_title', models.CharField(max_length=250)),
                ('inquery_content', models.TextField()),
                ('inquery_post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
