# Generated by Django 3.2.3 on 2021-06-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Classifier', '0022_inquieries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentiveoffers',
            name='offer_users',
        ),
    ]
